name: main_pr_opened
on:
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - "packages/**"
jobs:
  ci:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache: pnpm
      # install
      - run: pnpm i --frozen-lockfile
      # lint
      - run: pnpm run apps:lint
      # build
      - run: pnpm run apps:build
      # test
      - run: pnpm run apps:test
